/**
 * generated by Xtext 2.10.0
 */
package org.example.xtext;

import org.example.xtext.ModelDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ModelDslStandaloneSetup extends ModelDslStandaloneSetupGenerated {
  public static void doSetup() {
    ModelDslStandaloneSetup _modelDslStandaloneSetup = new ModelDslStandaloneSetup();
    _modelDslStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
