/**
 * generated by Xtext 2.10.0
 */
package org.example.xtext;

import org.example.xtext.AbstractModelDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ModelDslRuntimeModule extends AbstractModelDslRuntimeModule {
}
