/**
 * generated by Xtext 2.10.0
 */
package org.example.xtext.modelDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.example.xtext.modelDsl.ModelDslPackage#getProperty()
 * @model
 * @generated
 */
public interface Property extends Feature
{
} // Property
