/*
 * generated by Xtext 2.10.0
 */
package org.example.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ModelDslStandaloneSetup extends ModelDslStandaloneSetupGenerated {

	def static void doSetup() {
		new ModelDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
