/**
 * generated by Xtext 2.10.0
 */
package org.example.xtext.validation;

import org.example.xtext.validation.AbstractModelDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ModelDslValidator extends AbstractModelDslValidator {
}
